### ISSUE TITLE
The Border is Appearing while in full screen watching video etc YouTube

### ISSUE THREAD

**Issue by Shina-SG** [Shina-SG/Shina-Fox#4]
I will push this to the brand soon but for now you could replace at line 1098 to 1132 with this:
```css
/*============================================================================================*/
/* MAIN BROWSER */

/* Browser Border */

@media (prefers-color-scheme: dark) {
    #main-window:not([sizemode="fullscreen"]) #appcontent browser {
        border-radius: 15px !important;
        margin: 15px 15px 15px 15px !important;
        border: 3px solid rgba(0, 0, 0, 0);
        transition: border 0.3s ease;
        box-shadow: 0 0 10px 5px rgba(0,0,0,0.5);
    }

    #main-window:not([sizemode="fullscreen"]) #appcontent browser:hover {
        border: 3px solid rgba(204, 204, 204, 0.6);
        box-shadow: 0 0 10px 5px rgba(0,0,0,0.5);
    }
}

@media (prefers-color-scheme: light)  {
    #main-window:not([sizemode="fullscreen"]) #appcontent browser {
        border-radius: 15px !important;
        margin: 15px 15px 15px 15px !important;
        border: 3px solid rgba(51, 51, 51, 0.1);
        transition: border 0.3s ease;
        box-shadow: 0 0 10px 5px rgba(255,255,255,0.5);
    }

    #main-window:not([sizemode="fullscreen"]) #appcontent browser:hover {
        border: 3px solid rgba(51, 51, 51, 0.6);
        box-shadow: 0 0 10px 5px rgba(255,255,255,0.5);
    }
}
```
